[build]
builder = "DOCKERFILE"
dockerfilePath = "./python_backend/prod.Dockerfile"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
